@baseUrl = https://api.themeparks.wiki/v1

# wonderland
@entityID = 66f5d97a-a530-40bf-a712-a6317c96b06d

### ALL PARKS
GET {{baseUrl}}/destinations
Accept: application/json
Content-Type: application/json

### LIVE WAITING TIMES
GET {{baseUrl}}/entity/{{entityID}}/live
Accept: application/json
Content-Type: application/json

### PARK INFORMATION
GET {{baseUrl}}/entity/{{entityID}}
Accept: application/json
Content-Type: application/json

### PARK RIDE INFORMATION
GET {{baseUrl}}/entity/{{entityID}}/children
Accept: application/json
Content-Type: application/json

### PARK SCHEDULE
GET {{baseUrl}}/entity/{{entityID}}/schedule
Accept: application/json
Content-Type: application/json

### HISTORICAL
GET {{baseUrl}}/entity/{{entityID}}/schedule/2025/05/
Accept: application/json
Content-Type: application/json