using System.Diagnostics;
using System.Runtime.CompilerServices;
using Microsoft.Extensions.DependencyInjection;
using Microsoft.Extensions.Localization;

namespace ShinyWonderland.Tests;

// NOTE: IMediator, IMediatorContext, INavigator, and CacheContext cannot be generated by
// the Imposter 0.1.9 source generator due to generator bugs (C# keyword `event` not escaped,
// compiler-generated <Clone>$ name on records, params-after-optional mismatch).
// These hand-rolled test doubles cover the subset of behavior exercised by the test suite.

/// <summary>
/// Minimal IMediator test double. Configure responses with <see cref="SetupRequest"/>
/// and inspect calls via the <see cref="SentCommands"/> / <see cref="PublishedEvents"/> lists.
/// </summary>
public class TestMediator : IMediator
{
    readonly Dictionary<Type, Delegate> requestHandlers = new();
    public List<object> SentCommands { get; } = new();
    public List<object> PublishedEvents { get; } = new();
    public List<object> Requests { get; } = new();

    /// <summary>Register a handler for a specific request type.</summary>
    public TestMediator SetupRequest<TRequest, TResult>(Func<TRequest, TResult> handler)
        where TRequest : IRequest<TResult>
    {
        requestHandlers[typeof(TRequest)] = handler;
        return this;
    }

    /// <summary>Register a fixed result for all requests of the given type.</summary>
    public TestMediator SetupRequest<TRequest, TResult>(TResult result)
        where TRequest : IRequest<TResult>
        => SetupRequest<TRequest, TResult>(_ => result);

    public Task<(IMediatorContext Context, TResult Result)> Request<TResult>(
        IRequest<TResult> request,
        CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
    {
        Requests.Add(request);
        var ctx = new TestMediatorContext();
        configure?.Invoke(ctx);

        TResult result = default!;
        if (requestHandlers.TryGetValue(request.GetType(), out var handler))
            result = (TResult)handler.DynamicInvoke(request)!;

        return Task.FromResult(((IMediatorContext)ctx, result));
    }

    public async IAsyncEnumerable<(IMediatorContext Context, TResult Result)> Request<TResult>(
        IStreamRequest<TResult> request,
        [EnumeratorCancellation] CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
    {
        await Task.CompletedTask;
        yield break;
    }

    public Task<IMediatorContext> Send<TCommand>(
        TCommand request,
        CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
        where TCommand : ICommand
    {
        SentCommands.Add(request!);
        var ctx = new TestMediatorContext();
        configure?.Invoke(ctx);
        return Task.FromResult<IMediatorContext>(ctx);
    }

    public Task<IMediatorContext> Publish<TEvent>(
        TEvent @event,
        CancellationToken cancellationToken = default,
        bool executeInParallel = false,
        Action<IMediatorContext>? configure = null)
        where TEvent : IEvent
    {
        PublishedEvents.Add(@event!);
        var ctx = new TestMediatorContext();
        configure?.Invoke(ctx);
        return Task.FromResult<IMediatorContext>(ctx);
    }

    public void PublishToBackground<TEvent>(
        TEvent @event,
        bool executeInParallel = false,
        Action<IMediatorContext>? configure = null)
        where TEvent : IEvent
        => PublishedEvents.Add(@event!);

    public IDisposable Subscribe<TEvent>(
        Func<TEvent, IMediatorContext, CancellationToken, Task> action)
        where TEvent : IEvent
        => throw new NotImplementedException("Subscribe not supported by TestMediator");
}


/// <summary>
/// Minimal IMediatorContext test double. Only Headers is functional so the
/// Cache() extension method works; all other members are minimally populated
/// or throw for unsupported operations.
/// </summary>
public class TestMediatorContext : IMediatorContext
{
    readonly Dictionary<string, object> headers = new();

    public Guid Id { get; } = Guid.NewGuid();
    public IServiceScope ServiceScope { get; set; } = null!;
    public Exception? Exception { get; set; }
    public Activity? Activity { get; set; }
    public object Message { get; set; } = null!;
    public object? MessageHandler { get; set; }
    public IReadOnlyDictionary<string, object> Headers => headers;
    public IMediatorContext? Parent { get; set; }
    public IReadOnlyList<IMediatorContext> ChildContexts { get; } = Array.Empty<IMediatorContext>();
    public DateTimeOffset CreatedAt { get; } = DateTimeOffset.UtcNow;
    public bool BypassExceptionHandlingEnabled { get; set; }
    public bool BypassMiddlewareEnabled { get; set; }

    public void AddHeader(string key, object value) => headers[key] = value;
    public void RemoveHeader(string key) => headers.Remove(key);
    public void ClearHeaders() => headers.Clear();

    public IMediatorContext CreateChild(object newMessage, bool newScope = false)
        => throw new NotImplementedException();
    public Activity? StartActivity(string activityName) => null;
    public T TryGetValue<T>(string key)
    {
        if (headers.TryGetValue(key, out var v) && v is T t)
            return t;
        return default!;
    }
    public void Rebuild(IServiceScope scope, Activity? activity) { }

    public Task<TResult> Request<TResult>(
        IRequest<TResult> request,
        CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
        => throw new NotImplementedException();

    public Task Send<TCommand>(
        TCommand command,
        CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
        where TCommand : ICommand
        => throw new NotImplementedException();

    public Task Publish<TEvent>(
        TEvent @event,
        bool executeInParallel = false,
        CancellationToken cancellationToken = default,
        Action<IMediatorContext>? configure = null)
        where TEvent : IEvent
        => throw new NotImplementedException();

    public void PublishToBackground<TEvent>(
        TEvent @event,
        bool executeInParallel = false,
        Action<IMediatorContext>? configure = null)
        where TEvent : IEvent
        => throw new NotImplementedException();
}


/// <summary>Minimal INavigator test double that records navigation calls.</summary>
public class TestNavigator : INavigator
{
    public List<string> NavigateToCalls { get; } = new();
    public List<Type> NavigateToViewModelCalls { get; } = new();
    public int PopToRootCount { get; private set; }
    public int GoBackCount { get; private set; }

    public event EventHandler<Shiny.NavigationEventArgs>? Navigating;
    public event EventHandler<Shiny.NavigatedEventArgs>? Navigated;

    public INavigationBuilder CreateBuilder(bool fromRoot = false)
        => throw new NotImplementedException();

    public Task<bool> NavigateTo(
        string route,
        bool relativeNavigation = true,
        bool bypassInterceptors = false,
        CancellationToken cancellationToken = default,
        params IEnumerable<(string Key, object Value)> args)
    {
        NavigateToCalls.Add(route);
        return Task.FromResult(true);
    }

    public Task<bool> NavigateTo<TViewModelTarget>(
        Action<TViewModelTarget>? configure = null,
        bool relativeNavigation = true,
        bool bypassInterceptors = false,
        CancellationToken cancellationToken = default,
        params IEnumerable<(string Key, object Value)> args)
    {
        NavigateToViewModelCalls.Add(typeof(TViewModelTarget));
        return Task.FromResult(true);
    }

    Task<DialogResult<T>> INavigator.ShowDialog<TViewModel, T>(
        Action<TViewModel>? configure,
        CancellationToken cancellationToken)
        => throw new NotImplementedException();

    public Task<bool> PopToRoot(params IEnumerable<(string Key, object Value)> args)
        => PopToRoot(false, default, args);

    public Task<bool> PopToRoot(
        bool bypassInterceptors,
        CancellationToken cancellationToken = default,
        params IEnumerable<(string Key, object Value)> args)
    {
        PopToRootCount++;
        return Task.FromResult(true);
    }

    public Task<bool> GoBack(params IEnumerable<(string Key, object Value)> args)
        => GoBack(1, false, default, args);

    public Task<bool> GoBack(int backCount, params IEnumerable<(string Key, object Value)> args)
        => GoBack(backCount, false, default, args);

    public Task<bool> GoBack(
        int backCount,
        bool bypassInterceptors,
        CancellationToken cancellationToken = default,
        params IEnumerable<(string Key, object Value)> args)
    {
        GoBackCount += backCount;
        return Task.FromResult(true);
    }

    public Task SwitchShell(Microsoft.Maui.Controls.Shell shell) => Task.CompletedTask;
    public Task SwitchShell<TShell>() where TShell : Microsoft.Maui.Controls.Shell => Task.CompletedTask;

    public Task SetTabBadge(string route, int value) => Task.CompletedTask;
    public Task SetTabBadge<TViewModel>(int value) => Task.CompletedTask;
    public Task ClearTabBadge(string route) => Task.CompletedTask;
    public Task ClearTabBadge<TViewModel>() => Task.CompletedTask;

    // Suppress unused-event warnings
    void RaiseEvents()
    {
        Navigating?.Invoke(this, null!);
        Navigated?.Invoke(this, null!);
    }
}


/// <summary>IAppInfo test double - the static AppInfo throws outside of a MAUI platform head.</summary>
public class TestAppInfo : Microsoft.Maui.ApplicationModel.IAppInfo
{
    public int ShowSettingsUICount { get; private set; }

    public string PackageName => "com.shiny.wonderland.tests";
    public string Name => "ShinyWonderland.Tests";
    public string VersionString => "1.0.0";
    public Version Version => new(1, 0, 0);
    public string BuildString => "1";
    public void ShowSettingsUI() => ShowSettingsUICount++;
    public Microsoft.Maui.ApplicationModel.AppTheme RequestedTheme => Microsoft.Maui.ApplicationModel.AppTheme.Unspecified;
    public Microsoft.Maui.ApplicationModel.AppPackagingModel PackagingModel => Microsoft.Maui.ApplicationModel.AppPackagingModel.Packaged;
    public Microsoft.Maui.ApplicationModel.LayoutDirection RequestedLayoutDirection => Microsoft.Maui.ApplicationModel.LayoutDirection.LeftToRight;
}


/// <summary>IFileSystem test double backed by a fresh temp directory.</summary>
public class TestFileSystem : Microsoft.Maui.Storage.IFileSystem
{
    readonly string root = Directory.CreateTempSubdirectory("wonderland-tests-").FullName;

    public string CacheDirectory => Path.Combine(root, "cache");
    public string AppDataDirectory => root;

    public Task<Stream> OpenAppPackageFileAsync(string filename)
        => Task.FromResult<Stream>(File.OpenRead(Path.Combine(root, filename)));

    public Task<bool> AppPackageFileExistsAsync(string filename)
        => Task.FromResult(File.Exists(Path.Combine(root, filename)));
}


/// <summary>
/// In-memory IStringLocalizer used by the StringsLocalized wrapper. Returns
/// the key itself when no explicit translation is provided.
/// </summary>
public class TestStringLocalizer<T> : IStringLocalizer<T>
{
    readonly Dictionary<string, string> strings;

    public TestStringLocalizer(Dictionary<string, string>? strings = null)
        => this.strings = strings ?? new();

    public LocalizedString this[string name]
        => new(name, strings.GetValueOrDefault(name, name));

    public LocalizedString this[string name, params object[] arguments]
        => new(name, string.Format(strings.GetValueOrDefault(name, name), arguments));

    public IEnumerable<LocalizedString> GetAllStrings(bool includeParentCultures)
        => strings.Select(kvp => new LocalizedString(kvp.Key, kvp.Value));
}


public static class TestLocalization
{
    public static StringsLocalized Create(Dictionary<string, string>? overrides = null)
        => new(new TestStringLocalizer<Strings>(overrides));
}
